job_name: scouter
combat_level: 60
expedition_stat: 637
crit: 632
special: 1776
swift: 53
weapon_pdamage: 23.45
gear_status:
  head:
    base_item_level: 1390
    grade: relic
    upgrade: 16
  shoulder:
    base_item_level: 1390
    grade: relic
    upgrade: 17
  top:
    base_item_level: 1390
    grade: relic
    upgrade: 16
  bottom:
    base_item_level: 1390
    grade: relic
    upgrade: 16
  glove:
    base_item_level: 1390
    grade: ancient
    upgrade: 17
  weapon:
    base_item_level: 1390
    grade: ancient
    upgrade: 20
accessory_status:
  necklace: relic
  ear1: relic
  ear2: relic
  ring1: relic
  ring2: relic
avatar_status:
  head: epic
  top: epic
  bottom: epic
  weapon: epic

setitem_status:
  환각:
    level1: 6
    level2: 6
engraving_status:
  원한: 3
  바리케이드: 3
  돌격대장: 3
  예리한 둔기: 3
  아드레날린: 3
  진화의 유산: 1
card_status:
  - 남겨진 바람의 절벽 (12)
skill_status:
  "명령 : 레이드 미사일":
    level: 12
    gem: 7
    tripod:
      오르간 미사일: 4
      약점 포착: 4
  "명령 : 베이비 드론":
    level: 12
    gem: 0
    tripod:
      급소 공격: 4
      일제 공격: 5
  코멧 스트라이크:
    level: 12
    gem: 9
  슬러그 샷:
    level: 12
    gem: 9
  레이저 블레이드:
    level: 12
    gem: 9
    additional_stat:
      pdamage_indep: 20 # Q-E 연계 20%
  엑셀리온 빔:
    level: 12
    gem: 9
  버스트 블로우:
    level: 12
    gem: 9
  크림슨 브레이커:
    level: 12
    gem: 9
