from loasim.core.stat import InternalStat
from loasim.gear.base import Gear, GearRepository


lostark_gear_repository = GearRepository()

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="head",
        internal_stat_list=[
            InternalStat(stat_main=9466),
            InternalStat(stat_main=9562),
            InternalStat(stat_main=9658),
            InternalStat(stat_main=9755),
            InternalStat(stat_main=9853),
            InternalStat(stat_main=9952),
            InternalStat(stat_main=10052),
            InternalStat(stat_main=10153),
            InternalStat(stat_main=10255),
            InternalStat(stat_main=10358),
            InternalStat(stat_main=10462),
            InternalStat(stat_main=10567),
            InternalStat(stat_main=10674),
            InternalStat(stat_main=10781),
            InternalStat(stat_main=10889),
            InternalStat(stat_main=10999),
            InternalStat(stat_main=11993),
            InternalStat(stat_main=13077),
            InternalStat(stat_main=14259),
            InternalStat(stat_main=15547),
            InternalStat(stat_main=16951),
            InternalStat(stat_main=18412),
            InternalStat(stat_main=19873),
            InternalStat(stat_main=21335),
            InternalStat(stat_main=22796),
            InternalStat(stat_main=24257),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="top",
        internal_stat_list=[
            InternalStat(stat_main=7282),
            InternalStat(stat_main=7355),
            InternalStat(stat_main=7429),
            InternalStat(stat_main=7504),
            InternalStat(stat_main=7579),
            InternalStat(stat_main=7655),
            InternalStat(stat_main=7732),
            InternalStat(stat_main=7810),
            InternalStat(stat_main=7889),
            InternalStat(stat_main=7968),
            InternalStat(stat_main=8048),
            InternalStat(stat_main=8129),
            InternalStat(stat_main=8211),
            InternalStat(stat_main=8293),
            InternalStat(stat_main=8376),
            InternalStat(stat_main=8461),
            InternalStat(stat_main=9226),
            InternalStat(stat_main=10060),
            InternalStat(stat_main=10969),
            InternalStat(stat_main=11959),
            InternalStat(stat_main=13039),
            InternalStat(stat_main=14163),
            InternalStat(stat_main=15287),
            InternalStat(stat_main=16411),
            InternalStat(stat_main=17535),
            InternalStat(stat_main=18659),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="bottom",
        internal_stat_list=[
            InternalStat(stat_main=8010),
            InternalStat(stat_main=8091),
            InternalStat(stat_main=8172),
            InternalStat(stat_main=8254),
            InternalStat(stat_main=8337),
            InternalStat(stat_main=8421),
            InternalStat(stat_main=8506),
            InternalStat(stat_main=8591),
            InternalStat(stat_main=8677),
            InternalStat(stat_main=8765),
            InternalStat(stat_main=8853),
            InternalStat(stat_main=8942),
            InternalStat(stat_main=9032),
            InternalStat(stat_main=9122),
            InternalStat(stat_main=9214),
            InternalStat(stat_main=9307),
            InternalStat(stat_main=10148),
            InternalStat(stat_main=11066),
            InternalStat(stat_main=12065),
            InternalStat(stat_main=13155),
            InternalStat(stat_main=14343),
            InternalStat(stat_main=15580),
            InternalStat(stat_main=16816),
            InternalStat(stat_main=18052),
            InternalStat(stat_main=19289),
            InternalStat(stat_main=20525),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="glove",
        internal_stat_list=[
            InternalStat(stat_main=11651),
            InternalStat(stat_main=11768),
            InternalStat(stat_main=11886),
            InternalStat(stat_main=12006),
            InternalStat(stat_main=12126),
            InternalStat(stat_main=12248),
            InternalStat(stat_main=12372),
            InternalStat(stat_main=12496),
            InternalStat(stat_main=12621),
            InternalStat(stat_main=12748),
            InternalStat(stat_main=12876),
            InternalStat(stat_main=13006),
            InternalStat(stat_main=13137),
            InternalStat(stat_main=13269),
            InternalStat(stat_main=13402),
            InternalStat(stat_main=13537),
            InternalStat(stat_main=14761),
            InternalStat(stat_main=16095),
            InternalStat(stat_main=17549),
            InternalStat(stat_main=19135),
            InternalStat(stat_main=20863),
            InternalStat(stat_main=22661),
            InternalStat(stat_main=24459),
            InternalStat(stat_main=26258),
            InternalStat(stat_main=28056),
            InternalStat(stat_main=29854),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="shoulder",
        internal_stat_list=[
            InternalStat(stat_main=10194),
            InternalStat(stat_main=10297),
            InternalStat(stat_main=10401),
            InternalStat(stat_main=10505),
            InternalStat(stat_main=10611),
            InternalStat(stat_main=10717),
            InternalStat(stat_main=10825),
            InternalStat(stat_main=10934),
            InternalStat(stat_main=11044),
            InternalStat(stat_main=11155),
            InternalStat(stat_main=11267),
            InternalStat(stat_main=11380),
            InternalStat(stat_main=11495),
            InternalStat(stat_main=11610),
            InternalStat(stat_main=11727),
            InternalStat(stat_main=11845),
            InternalStat(stat_main=12916),
            InternalStat(stat_main=14083),
            InternalStat(stat_main=15356),
            InternalStat(stat_main=16743),
            InternalStat(stat_main=18255),
            InternalStat(stat_main=19829),
            InternalStat(stat_main=21402),
            InternalStat(stat_main=22976),
            InternalStat(stat_main=24549),
            InternalStat(stat_main=26123),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1340_relic",
        slot="weapon",
        internal_stat_list=[
            InternalStat(weapon_att=17574),
            InternalStat(weapon_att=17750),
            InternalStat(weapon_att=17927),
            InternalStat(weapon_att=18107),
            InternalStat(weapon_att=18288),
            InternalStat(weapon_att=18470),
            InternalStat(weapon_att=18655),
            InternalStat(weapon_att=18842),
            InternalStat(weapon_att=19030),
            InternalStat(weapon_att=19220),
            InternalStat(weapon_att=19413),
            InternalStat(weapon_att=19607),
            InternalStat(weapon_att=19803),
            InternalStat(weapon_att=20001),
            InternalStat(weapon_att=20201),
            InternalStat(weapon_att=20403),
            InternalStat(weapon_att=22239),
            InternalStat(weapon_att=24241),
            InternalStat(weapon_att=26422),
            InternalStat(weapon_att=28800),
            InternalStat(weapon_att=31392),
            InternalStat(weapon_att=34090),
            InternalStat(weapon_att=36787),
            InternalStat(weapon_att=39485),
            InternalStat(weapon_att=42182),
            InternalStat(weapon_att=44880),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="head",
        internal_stat_list=[
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(stat_main=17339),  # +10
            InternalStat(stat_main=18122),
            InternalStat(stat_main=18940),
            InternalStat(stat_main=19795),
            InternalStat(stat_main=20688),
            InternalStat(stat_main=21621),
            InternalStat(stat_main=22596),
            InternalStat(stat_main=23615),
            InternalStat(stat_main=24681),
            InternalStat(stat_main=25794),
            InternalStat(stat_main=26957),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="top",
        internal_stat_list=[
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(stat_main=13338),  # +10
            InternalStat(stat_main=13940),
            InternalStat(stat_main=14569),
            InternalStat(stat_main=15227),
            InternalStat(stat_main=15914),
            InternalStat(stat_main=16632),
            InternalStat(stat_main=17382),
            InternalStat(stat_main=18166),
            InternalStat(stat_main=18985),
            InternalStat(stat_main=19841),
            InternalStat(stat_main=20736),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="bottom",
        internal_stat_list=[
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(stat_main=14672),  # +10
            InternalStat(stat_main=15334),
            InternalStat(stat_main=16026),
            InternalStat(stat_main=16749),
            InternalStat(stat_main=17505),
            InternalStat(stat_main=18295),
            InternalStat(stat_main=19120),
            InternalStat(stat_main=19982),
            InternalStat(stat_main=20884),
            InternalStat(stat_main=21825),
            InternalStat(stat_main=22810),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="glove",
        internal_stat_list=[
            InternalStat(stat_main=12876),
            InternalStat(stat_main=13137),
            InternalStat(stat_main=13402),
            InternalStat(stat_main=13933),
            InternalStat(stat_main=14761),
            InternalStat(stat_main=15637),
            InternalStat(stat_main=16566),
            InternalStat(stat_main=17549),
            InternalStat(stat_main=18591),
            InternalStat(stat_main=20419),
            InternalStat(stat_main=21341),
            InternalStat(stat_main=22304),
            InternalStat(stat_main=23310),
            InternalStat(stat_main=24362),
            InternalStat(stat_main=25462),
            InternalStat(stat_main=26610),
            InternalStat(stat_main=27811),
            InternalStat(stat_main=29065),
            InternalStat(stat_main=30376),
            InternalStat(stat_main=31746),
            InternalStat(stat_main=33177),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="shoulder",
        internal_stat_list=[
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(),
            InternalStat(stat_main=18673),  # +10
            InternalStat(stat_main=19516),
            InternalStat(stat_main=20397),
            InternalStat(stat_main=21317),
            InternalStat(stat_main=22279),
            InternalStat(stat_main=23284),
            InternalStat(stat_main=24334),
            InternalStat(stat_main=25432),
            InternalStat(stat_main=26579),
            InternalStat(stat_main=27778),
            InternalStat(stat_main=29030),
        ],
    )
)

lostark_gear_repository.add(
    Gear(
        grade="t3_1390_relic",
        slot="weapon",
        internal_stat_list=[
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=0),
            InternalStat(weapon_att=32109),  # +10
            InternalStat(weapon_att=33554),
            InternalStat(weapon_att=35064),
            InternalStat(weapon_att=36641),
            InternalStat(weapon_att=38290),
            InternalStat(weapon_att=40013),
            InternalStat(weapon_att=41814),
            InternalStat(weapon_att=43696),
            InternalStat(weapon_att=45662),
            InternalStat(weapon_att=47717),
            InternalStat(weapon_att=49864),
        ],
    )
)
